version: '3.8'

services:
  nextjs-app:
    build:
      context: . 
      dockerfile: Dockerfile    
    ports:
      - "3000:3000" 
    environment:
      NEXT_PUBLIC_SUPABASE_URL: "http://127.0.0.1:54321" 
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz" 
    